

# classes of disease
disease_classes = ['Apple_scab',
                   'Black_rot',
                   'Cedar_apple_rust',
                   'Healthy',
                   'Healthy',
                   '(including_sour)___Powdery_mildew',
                   'Healthy',
                   'Cercospora_leaf_spot Gray_leaf_spot',
                   'Common_rust_',
                   'Northern_Leaf_Blight',
                   'Healthy',
                   'Black_rot',
                   'Esca_(Black_Measles)',
                   'Leaf_blight_(Isariopsis_Leaf_Spot)',
                   'Healthy',
                   'Haunglongbing_(Citrus_greening)',
                   'Bacterial_spot',
                   'Healthy',
                   '_bell___Bacterial_spot',
                   'Healthy',
                   'Early_blight',
                   'Late_blight',
                   'Healthy',
                   'Healthy',
                   'Healthy',
                   'Powdery_mildew',
                   'Leaf_scorch',
                   'Healthy',
                   'Bacterial_spot',
                   'Early_blight',
                   'Late_blight',
                   'Leaf_Mold',
                   'Septoria_leaf_spot',
                   'Spider_mites Two-spotted_spider_mite',
                   'Target_Spot',
                   'Tomato_Yellow_Leaf_Curl_Virus',
                   'Tomato_mosaic_virus',
                   'Healthy']


# category
plant_category = [
    'Apple',
    'Blueberry',
    'Cherry_(including_sour)',
    'Corn_(maize)',
    'Grape',
    'Orange',
    'Peach',
    'Pepper,',
    'Potato',
    'Raspberry',
    'Soybean',
    'Squash',
    'Strawberry',
    'Tomato'
    ]